src/Entity/Location.php
<?php

namespace App\Entity;

use App\Repository\LocationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LocationRepository::class)]
class Location
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateD_location = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ? int $penalite = null;

    #[ORM\Column(length: 255)]
    private ? int $delaisPaiem = null;

    #[ORM\Column(length: 255)]
    private ? float $causionEnt = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ? float $causionSort = null;

    #[ORM\Column(length: 255)]
    private ?string $etatLieuFile = null;

    #[ORM\ManyToOne(inversedBy: 'locations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Propriete $propriete = null;

    #[ORM\ManyToOne(inversedBy: 'locations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $locataire = null;

    #[ORM\Column(length: 255)]
    private ?string $mois = null;

    #[ORM\Column]
    private ?int $annee = null;

    #[ORM\Column(length: 255)]
    private ?string $moisAvance = null;

    #[ORM\OneToMany(mappedBy: 'location', targetEntity: Loyer::class)]
    private Collection $loyers;

    public function __construct()
    {
        $this->loyers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDLocation(): ?\DateTimeInterface
    {
        return $this->dateD_location;
    }

    public function setDateDLocation(\DateTimeInterface $dateD_location): static
    {
        $this->dateD_location = $dateD_location;

        return $this;
    }

    public function getPenalite(): ? int
    {
        return $this->penalite;
    }

    public function setPenalite(?int $penalite): static
    {
        $this->penalite = $penalite;

        return $this;
    }

    public function getDelaisPaiem(): ?int
    {
        return $this->delaisPaiem;
    }

    public function setDelaisPaiem(int $delaisPaiem): static
    {
        $this->delaisPaiem = $delaisPaiem;

        return $this;
    }

    public function getCausionEnt(): ?float
    {
        return $this->causionEnt;
    }

    public function setCausionEnt(float $causionEnt): static
    {
        $this->causionEnt = $causionEnt;

        return $this;
    }

    public function getCausionSort(): ?float
    {
        return $this->causionSort;
    }

    public function setCausionSort(float $causionSort): static
    {
        $this->causionSort = $causionSort;

        return $this;
    }

    public function getEtatLieuFile(): ?string
    {
        return $this->etatLieuFile;
    }

    public function setEtatLieu(string $etatLieuFile): static
    {
        $this->etatLieuFile = $etatLieuFile;

        return $this;
    }

    public function getPropriete(): ?Propriete
    {
        return $this->propriete;
    }

    public function setPropriete(?Propriete $propriete): static
    {
        $this->propriete = $propriete;

        return $this;
    }

    public function getLocataire(): ?User
    {
        return $this->locataire;
    }

    public function setLocataire(?User $locataire): static
    {
        $this->locataire = $locataire;

        return $this;
    }

    public function __toString()
    {
       return $this->delaisPaiem;
    }

    public function getMois(): ?string
    {
        return $this->mois;
    }

    public function setMois(string $mois): static
    {
        $this->mois = $mois;

        return $this;
    }

    public function getAnnee(): ?int
    {
        return $this->annee;
    }

    public function setAnnee(int $annee): static
    {
        $this->annee = $annee;

        return $this;
    }

    public function getMoisAvance(): ?string
    {
        return $this->moisAvance;
    }

    public function setMoisAvance(string $moisAvance): static
    {
        $this->moisAvance = $moisAvance;

        return $this;
    }

    /**
     * @return Collection<int, Loyer>
     */
    public function getLoyers(): Collection
    {
        return $this->loyers;
    }

    public function addLoyer(Loyer $loyer): static
    {
        if (!$this->loyers->contains($loyer)) {
            $this->loyers->add($loyer);
            $loyer->setLocation($this);
        }

        return $this;
    }

    public function removeLoyer(Loyer $loyer): static
    {
        if ($this->loyers->removeElement($loyer)) {
            // set the owning side to null (unless already changed)
            if ($loyer->getLocation() === $this) {
                $loyer->setLocation(null);
            }
        }

        return $this;
    }

   

}

src/Form/LocationType.php
<?php

namespace App\Form;
use App\Entity\Location;
use App\Entity\Propriete;
use App\Entity\User;
use App\Repository\ProprieteRepository;
use App\Repository\UserRepository;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Doctrine\ORM\QueryBuilder;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LocationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $year = date('Y') ;
        $listYears = [] ;

        for($i = $year; $i > ($year-2) ; $i--){
            $listYears[$i] = [$i] ;
        }

        $builder
            ->add('dateD_location', DateType::class,[
                'attr'=> [
                    'class'=>"form-control"
                ], 
                'label' => "Date de Location",
                'widget' => 'single_text',
            ])
            ->add('penalite', IntegerType::class,[
                'attr' => [
                    'class' => "form-control",
                ], 
                'label' => "Pénalité (%)",
                'required' => false
            ])
            ->add('delaisPaiem', IntegerType::class,[
                'attr'=> [
                    'class'=>"form-control",
                    'min'=> 1
                ],
                    'label' => "Délai de paiement"
               
            ])

            ->add('mois', ChoiceType::class,[
              'attr'=>[
                'class'=>"form-control"
              ],
              'label' => "Mois de départ de la location",
              'choices' => [
                'Janvier' => '01',
                'Février' => '02',
                'Mars' => '03'
              ]

            ])

            ->add('annee', ChoiceType::class, [
                'attr'=>[
                  'class'=>'form-control'
                ],
                'label'=>'Année de la location',
                'choices' => [
                    2023 => 2023,
                    2022 => 2022
                ]
            ])

            ->add('modePaiem', ChoiceType::class, [
                'attr'=>[
                  'class'=>'form-control'
                ],
                'mapped' => false,
                'label'=>'Mode de paiement',
                'choices' => [
                    "Orange Money" => "Orange Money",
                    "Espèces" => "Espèces",
                ]
            ])
            ->add('moisAvance', IntegerType::class,[
                'attr'=>[
                    'class'=>'form-control',
                    'min' => 1
                ],
                'label'=>"Nombre de mois d'avance",
                'required' => true
            ])
            ->add('causionEnt', null ,[
                'attr' => [
                    'class' => 'form-control'
                ],
                'label' => "Caution d'entrée"
            ])
          
            ->add('etatLieu',FileType::class, [
                'label' => 'Etat des lieu',
                'mapped' => false,
                'required' => $options['attrRequired'],
                'attr' => [
                    'class' => 'form-control'
                    ]
            ] )
            ->add('propriete', EntityType::class,[
                'class' => Propriete::class,
                'query_builder' => function (ProprieteRepository $er): QueryBuilder {
                    return $er->createQueryBuilder('i')
                        ->orderBy('i.nomPro ', 'ASC');
                },
                'attr' => [
                    'class' => "form-control"
                ],

                'choice_label' => 'nomPro ',
            
                ])
            ->add('locataire',EntityType::class,[
                'class' => User::class,
                'query_builder' => function (UserRepository $er): QueryBuilder {
                    return $er->createQueryBuilder('i')
                        ->orderBy('i.nom ', 'ASC');
                },
                'attr' => [
                    'class' => "form-control"
                ],
                'label' => "Locataire"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Location::class,
            'attrRequired' => true
        ]);
    }
}

src/Controller/LocationController.php
<?php

namespace App\Controller;

use App\Entity\Location;
use App\Form\LocationType;
use App\Repository\LocationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/location')]
class LocationController extends AbstractController
{
    #[Route('/', name: 'app_location_index', methods: ['GET'])]
    public function index(LocationRepository $locationRepository): Response
    {
        return $this->render('location/index.html.twig', [
            'locations' => $locationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_location_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $location = new Location();
        $form = $this->createForm(LocationType::class, $location);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($location);
            $entityManager->flush();

            return $this->redirectToRoute('app_location_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('location/new.html.twig', [
            'location' => $location,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_location_show', methods: ['GET'])]
    public function show(Location $location): Response
    {
        return $this->render('location/show.html.twig', [
            'location' => $location,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_location_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Location $location, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LocationType::class, $location);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_location_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('location/edit.html.twig', [
            'location' => $location,
            'form' => $form,
        ]);
    }

    // #[Route('/{id}', name: 'app_location_delete', methods: ['POST'])]
    // public function delete(Request $request, Location $location, EntityManagerInterface $entityManager): Response
    // {
    //     if ($this->isCsrfTokenValid('delete'.$location->getId(), $request->request->get('_token'))) {
    //         $entityManager->remove($location);
    //         $entityManager->flush();
    //     }

    //     return $this->redirectToRoute('app_location_index', [], Response::HTTP_SEE_OTHER);
    // }
}

templates/location/_form.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}

templates/location/edit.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}Edit Location{% endblock %}

{% block body %}
    <h1>Edit Location</h1>

    {{ include('location/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_location_index') }}">back to list</a>

    {{ include('location/_delete_form.html.twig') }}
{% endblock %} #}

templates/location/index.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}Location index{% endblock %}

{% block body %}
    <h1>Location index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>DateD_location</th>
                <th>Penalite</th>
                <th>DelaisPaiem</th>
                <th>CausionEnt</th>
                <th>CausionSort</th>
                <th>EtatLieu</th>
                <th>DateL</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for location in locations %}
            <tr>
                <td>{{ location.id }}</td>
                <td>{{ location.dateDLocation ? location.dateDLocation|date('Y-m-d') : '' }}</td>
                <td>{{ location.penalite }}</td>
                <td>{{ location.delaisPaiem }}</td>
                <td>{{ location.causionEnt }}</td>
                <td>{{ location.causionSort }}</td>
                <td>{{ location.etatLieu }}</td>
                <td>{{ location.dateL ? location.dateL|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_location_show', {'id': location.id}) }}">show</a>
                    <a href="{{ path('app_location_edit', {'id': location.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_location_new') }}">Create new</a>
{% endblock %} #}

templates/location/new.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}New Location{% endblock %}

{% block body %}
    <h1>Create new Location</h1>

    {{ include('location/_form.html.twig') }}

    <a href="{{ path('app_location_index') }}">back to list</a>
{% endblock %} #}

templates/location/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Location{% endblock %}

{% block body %}
    <h1>Location</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ location.id }}</td>
            </tr>
            <tr>
                <th>DateD_location</th>
                <td>{{ location.dateDLocation ? location.dateDLocation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Penalite</th>
                <td>{{ location.penalite }}</td>
            </tr>
            <tr>
                <th>DelaisPaiem</th>
                <td>{{ location.delaisPaiem }}</td>
            </tr>
            <tr>
                <th>CausionEnt</th>
                <td>{{ location.causionEnt }}</td>
            </tr>
            <tr>
                <th>CausionSort</th>
                <td>{{ location.causionSort }}</td>
            </tr>
            <tr>
                <th>EtatLieu</th>
                <td>{{ location.etatLieu }}</td>
            </tr>
            <tr>
                <th>DateL</th>
                <td>{{ location.dateL ? location.dateL|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_location_index') }}">back to list</a>

    <a href="{{ path('app_location_edit', {'id': location.id}) }}">edit</a>

    {{ include('super_admin/_delete_form.html.twig') }}
{% endblock %}